//! Shell integration printed by `navkit init`. A child process cannot change
//! the parent shell's directory, so each shell gets a few lines that run
//! `navkit pick`, read the path it prints and cd there.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

type Error = Box<dyn std::error::Error>;

/// The four commands every shell gets, with the picker mode behind each.
const PICK_COMMANDS: [(&str, &str, &str); 3] = [
    (
        "c",
        "dirs",
        "pick a directory under the current one and cd into it",
    ),
    ("cf", "files", "pick a file and cd into its directory"),
    ("zi", "recent", "pick a directory from the zoxide history"),
];

pub fn powershell() -> Result<String, Error> {
    let exe = exe_path()?;
    // Single quotes are the only thing that needs escaping inside '...'.
    let exe = exe.to_string_lossy().replace('\'', "''");
    let mut out = String::new();
    out.push_str(
        r#"# navkit: c / cf / z / zi for PowerShell.
# Add this line to $PROFILE after zoxide init:
#   Invoke-Expression (& navkit init powershell | Out-String)

function global:Invoke-NavkitPick {
    param([string]$Mode, [string[]]$Query)
    # The query travels in an environment variable so that the same shim
    # shape works in cmd.exe, whose argument parsing eats ^ & | on the way.
    $env:NAVKIT_QUERY = ($Query -join ' ')
    $encoding = [Console]::OutputEncoding
    try {
        # navkit prints UTF-8; make sure paths with non-ASCII characters
        # come back intact on consoles that default to a legacy code page.
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $path = & '"#,
    );
    out.push_str(&exe);
    out.push_str(
        r#"' pick --mode $Mode
        if ($LASTEXITCODE -eq 0 -and $path) {
            Set-Location -LiteralPath $path
            if (Get-Command zoxide -ErrorAction SilentlyContinue) { zoxide add -- $path 2>$null }
        }
    } finally {
        [Console]::OutputEncoding = $encoding
        Remove-Item Env:NAVKIT_QUERY -ErrorAction SilentlyContinue
    }
}

function global:Invoke-NavkitJump {
    param([string[]]$Query)
    if (-not $Query) { Set-Location -LiteralPath $HOME; return }
    $path = zoxide query -- @Query
    if ($LASTEXITCODE -eq 0 -and $path) { Set-Location -LiteralPath $path }
}

# zoxide init defines z / zi as aliases, and aliases win over functions.
foreach ($name in 'z', 'zi') {
    if (Test-Path "Alias:$name") { Remove-Alias -Name $name -Force -ErrorAction SilentlyContinue }
}

"#,
    );
    for (name, mode, _) in PICK_COMMANDS {
        writeln!(
            out,
            "function global:{name:<2} {{ Invoke-NavkitPick {mode} $args }}"
        )?;
    }
    out.push_str("function global:z  { Invoke-NavkitJump $args }\n");
    Ok(out)
}

/// Returns `(file name, contents)` for each cmd.exe shim.
pub fn cmd() -> Result<Vec<(String, String)>, Error> {
    let exe = exe_path()?;
    let exe_dir = exe
        .parent()
        .ok_or("cannot determine the directory of navkit.exe")?
        .to_string_lossy()
        .into_owned();
    let mut files = Vec::new();
    for (name, mode, summary) in PICK_COMMANDS {
        files.push((
            format!("{name}.cmd"),
            cmd_pick(name, mode, summary, &exe_dir),
        ));
    }
    files.push(("z.cmd".to_string(), CMD_Z.to_string()));
    Ok(files)
}

pub fn write_cmd(dir: &Path) -> Result<Vec<PathBuf>, Error> {
    std::fs::create_dir_all(dir)?;
    let mut written = Vec::new();
    for (name, body) in cmd()? {
        let path = dir.join(name);
        std::fs::write(&path, body)?;
        written.push(path);
    }
    Ok(written)
}

fn cmd_pick(name: &str, mode: &str, summary: &str, exe_dir: &str) -> String {
    // Notes on the shape, learned the hard way with the batch-file version:
    // - navkit is called by bare name inside for /f. Quoting a full path
    //   there breaks once cmd /c sees a third quote character.
    // - The query goes through NAVKIT_QUERY. `call` and the for /f child
    //   cmd.exe each re-parse arguments and eat ^ & | on the way.
    // - The path is read back under code page 65001 because navkit prints
    //   UTF-8, then the original code page is restored.
    // - endlocal must run before cd, or the directory change is undone.
    format!(
        "@echo off\r\n\
         rem {name} [query] - {summary}.\r\n\
         rem Generated by \"navkit init cmd\".\r\n\
         setlocal\r\n\
         set \"PATH={exe_dir};%PATH%\"\r\n\
         set \"NAVKIT_QUERY=%*\"\r\n\
         for /f \"tokens=2 delims=:\" %%c in ('chcp') do set \"NAVKIT_CP=%%c\"\r\n\
         chcp 65001 >nul\r\n\
         for /f \"delims=\" %%p in ('navkit pick --mode {mode}') do (\r\n\
         \x20   chcp %NAVKIT_CP% >nul\r\n\
         \x20   zoxide add -- \"%%p\" 2>nul\r\n\
         \x20   endlocal\r\n\
         \x20   cd /d \"%%p\"\r\n\
         \x20   exit /b 0\r\n\
         )\r\n\
         chcp %NAVKIT_CP% >nul\r\n\
         endlocal\r\n\
         exit /b 1\r\n"
    )
}

const CMD_Z: &str = "@echo off\r\n\
rem z <keywords> - jump to a frequently used directory (zoxide history).\r\n\
rem Generated by \"navkit init cmd\".\r\n\
if \"%~1\"==\"\" cd /d \"%USERPROFILE%\" & exit /b 0\r\n\
for /f \"delims=\" %%p in ('zoxide query -- %*') do (\r\n\
\x20   cd /d \"%%p\"\r\n\
\x20   exit /b 0\r\n\
)\r\n\
exit /b 1\r\n";

fn exe_path() -> Result<PathBuf, Error> {
    let exe = std::env::current_exe()?;
    Ok(std::path::absolute(exe)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powershell_defines_the_four_commands_and_drops_aliases() {
        let out = powershell().unwrap();
        for f in [
            "function global:c ",
            "function global:cf",
            "function global:z ",
            "function global:zi",
        ] {
            assert!(out.contains(f), "missing {f}");
        }
        assert!(out.contains("Remove-Alias"));
        assert!(out.contains("param([string]$Mode, [string[]]$Query)"));
    }

    #[test]
    fn cmd_emits_four_files_with_the_exe_dir_on_path() {
        let files = cmd().unwrap();
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["c.cmd", "cf.cmd", "zi.cmd", "z.cmd"]);
        let (_, c) = &files[0];
        assert!(c.contains("navkit pick --mode dirs"));
        assert!(c.contains("set \"NAVKIT_QUERY=%*\""));
        assert!(!c.contains("'\""), "exe must not be quoted inside for /f");
        assert!(
            c.split('\n').all(|l| l.is_empty() || l.ends_with('\r')),
            "cmd files use CRLF"
        );
    }
}
