//! Shell integration printed by `tadoru init`. A child process cannot change
//! the parent shell's directory, so each shell gets a few lines that run
//! `tadoru pick`, read the path it prints and cd there.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

type Error = Box<dyn std::error::Error>;

/// The four commands every shell gets, with the picker mode behind each.
const PICK_COMMANDS: [(&str, &str, &str); 3] = [
    (
        "c",
        "dirs",
        "pick a directory under the current one and cd into it",
    ),
    ("cf", "files", "pick a file and cd into its directory"),
    ("zi", "recent", "pick a directory from the zoxide history"),
];

pub fn powershell() -> Result<String, Error> {
    let exe = exe_path()?;
    // Single quotes are the only thing that needs escaping inside '...'.
    let exe = exe.to_string_lossy().replace('\'', "''");
    let mut out = String::new();
    out.push_str(
        r#"# tadoru: c / cf / z / zi for PowerShell.
# Add this line to $PROFILE after zoxide init:
#   Invoke-Expression (& tadoru init powershell | Out-String)

function global:Invoke-TadoruPick {
    param([string]$Mode, [string[]]$Query)
    # The query travels in an environment variable so that the same shim
    # shape works in cmd.exe, whose argument parsing eats ^ & | on the way.
    $previousQuery = $env:TADORU_QUERY
    $env:TADORU_QUERY = ($Query -join ' ')
    $encoding = [Console]::OutputEncoding
    $exitCode = 2
    try {
        # tadoru prints UTF-8; make sure paths with non-ASCII characters
        # come back intact on consoles that default to a legacy code page.
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        $from = (Get-Location).Path
        if ($Mode -eq 'dirs' -and $Query.Count -eq 1 -and $Query[0] -eq '-') {
            if (-not $env:TADORU_PREVIOUS) { throw 'No previous tadoru directory yet.' }
            $path = $env:TADORU_PREVIOUS
            $exitCode = 0
        } else {
        $path = & '"#,
    );
    out.push_str(&exe);
    out.push_str(
        r#"' pick --mode $Mode
        $exitCode = $LASTEXITCODE
        }
        if ($exitCode -eq 0 -and $path) {
            Set-Location -LiteralPath $path -ErrorAction Stop
            if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
            if (Get-Command zoxide -ErrorAction SilentlyContinue) { zoxide add -- $path 2>$null }
        } elseif ($exitCode -eq 0) {
            $exitCode = 1
        }
    } catch {
        $exitCode = 2
        Write-Error $_
    } finally {
        [Console]::OutputEncoding = $encoding
        $env:TADORU_QUERY = $previousQuery
        $global:LASTEXITCODE = $exitCode
    }
}

function global:Invoke-TadoruJump {
    param([string[]]$Query)
    $encoding = [Console]::OutputEncoding
    $exitCode = 2
    try {
        $from = (Get-Location).Path
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        if (-not $Query) {
            Set-Location -LiteralPath $HOME -ErrorAction Stop
            $exitCode = 0
        } else {
            $path = zoxide query -- @Query
            $exitCode = $LASTEXITCODE
            if ($exitCode -eq 0 -and $path) { Set-Location -LiteralPath $path -ErrorAction Stop }
            elseif ($exitCode -eq 0) { $exitCode = 1 }
        }
        if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
    } catch {
        $exitCode = 2
        Write-Error $_
    } finally {
        [Console]::OutputEncoding = $encoding
        $global:LASTEXITCODE = $exitCode
    }
}

# zoxide init defines z / zi as aliases, and aliases win over functions.
foreach ($name in 'z', 'zi') {
    if (Test-Path "Alias:$name") { Remove-Alias -Name $name -Force -ErrorAction SilentlyContinue }
}

"#,
    );
    for (name, mode, _) in PICK_COMMANDS {
        writeln!(
            out,
            "function global:{name:<2} {{ Invoke-TadoruPick {mode} $args }}"
        )?;
    }
    out.push_str("function global:z  { Invoke-TadoruJump $args }\n");
    Ok(out)
}

/// Returns `(file name, contents)` for each PowerShell script shim. Dropped into a
/// PATH folder these work without touching the profile: a script's Set-Location
/// changes the caller's directory, unlike in POSIX shells.
pub fn powershell_scripts() -> Result<Vec<(String, String)>, Error> {
    let exe = exe_path()?;
    let exe = exe.to_string_lossy().replace('\'', "''");
    let mut files = Vec::new();
    for (name, mode, summary) in PICK_COMMANDS {
        let body = format!(
            r#"# {name} [query] - {summary}.
# Generated by "tadoru init powershell --out".
param([Parameter(ValueFromRemainingArguments)][string[]]$Query)
# A tadoru next to this script wins, so a release archive unpacked into a
# PATH folder works as is; the exe that generated the file is the fallback.
# Both names are tried because pwsh also runs where binaries carry no suffix.
$exe = $null
foreach ($candidate in 'tadoru.exe', 'tadoru') {{
    $sibling = Join-Path $PSScriptRoot $candidate
    if (Test-Path -LiteralPath $sibling -PathType Leaf) {{ $exe = $sibling; break }}
}}
if (-not $exe) {{ $exe = '{exe}' }}
$previousQuery = $env:TADORU_QUERY
$env:TADORU_QUERY = ($Query -join ' ')
$encoding = [Console]::OutputEncoding
$exitCode = 2
try {{
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    $from = (Get-Location).Path
    if ('{mode}' -eq 'dirs' -and $Query.Count -eq 1 -and $Query[0] -eq '-') {{
        if (-not $env:TADORU_PREVIOUS) {{ throw 'No previous tadoru directory yet.' }}
        $path = $env:TADORU_PREVIOUS
        $exitCode = 0
    }} else {{
    $path = & $exe pick --mode {mode}
    $exitCode = $LASTEXITCODE
    }}
    if ($exitCode -eq 0 -and $path) {{
        Set-Location -LiteralPath $path -ErrorAction Stop
        if ((Get-Location).Path -ne $from) {{ $env:TADORU_PREVIOUS = $from }}
        if (Get-Command zoxide -ErrorAction SilentlyContinue) {{ zoxide add -- $path 2>$null }}
    }} elseif ($exitCode -eq 0) {{
        $exitCode = 1
    }}
}} catch {{
    $exitCode = 2
    Write-Error $_
}} finally {{
    [Console]::OutputEncoding = $encoding
    $env:TADORU_QUERY = $previousQuery
    $global:LASTEXITCODE = $exitCode
}}
"#
        );
        files.push((format!("{name}.ps1"), body));
    }
    files.push((
        "z.ps1".to_string(),
        r#"# z <keywords> - jump to a frequently used directory (zoxide history).
# Generated by "tadoru init powershell --out".
param([Parameter(ValueFromRemainingArguments)][string[]]$Query)
$encoding = [Console]::OutputEncoding
$exitCode = 2
try {
    $from = (Get-Location).Path
    [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
    if (-not $Query) {
        Set-Location -LiteralPath $HOME -ErrorAction Stop
        $exitCode = 0
    } else {
        $path = zoxide query -- @Query
        $exitCode = $LASTEXITCODE
        if ($exitCode -eq 0 -and $path) { Set-Location -LiteralPath $path -ErrorAction Stop }
        elseif ($exitCode -eq 0) { $exitCode = 1 }
    }
    if ((Get-Location).Path -ne $from) { $env:TADORU_PREVIOUS = $from }
} catch {
    $exitCode = 2
    Write-Error $_
} finally {
    [Console]::OutputEncoding = $encoding
    $global:LASTEXITCODE = $exitCode
}
"#
        .to_string(),
    ));
    Ok(files)
}

pub fn write_powershell(dir: &Path) -> Result<Vec<PathBuf>, Error> {
    write_files(dir, powershell_scripts()?)
}

pub fn bash() -> Result<String, Error> {
    let exe = exe_path()?;
    // Forward slashes work in every bash, including the MSYS one on Windows.
    let exe = exe
        .to_string_lossy()
        .replace('\\', "/")
        .replace('\'', "'\\''");
    let mut out = String::new();
    out.push_str(
        r#"# tadoru: c / cf / z / zi for bash and zsh.
# Add this line to ~/.bashrc or ~/.zshrc after zoxide init:
#   eval "$(tadoru init bash)"

__tadoru_cd() {
    local before=$PWD
    cd -- "$1" || return 2
    if [ "$PWD" != "$before" ]; then export TADORU_PREVIOUS="$before"; fi
    return 0
}

__tadoru_pick() {
    local mode=$1
    shift
    if [ "$mode" = dirs ] && [ $# -eq 1 ] && [ "$1" = - ]; then
        if [ -z "${TADORU_PREVIOUS:-}" ]; then
            printf '%s\n' 'tadoru: no previous directory yet' >&2
            return 2
        fi
        __tadoru_cd "$TADORU_PREVIOUS"
        return $?
    fi
    local path
    # The query travels in an environment variable so that the same shim
    # shape works in cmd.exe, whose argument parsing eats ^ & | on the way.
    path=$(TADORU_QUERY="$*" '"#,
    );
    out.push_str(&exe);
    out.push_str(
        r#"' pick --mode "$mode") || return $?
    [ -n "$path" ] || return 1
    __tadoru_cd "$path" || return
    command -v zoxide >/dev/null 2>&1 && zoxide add -- "$path" 2>/dev/null
    return 0
}

__tadoru_jump() {
    if [ $# -eq 0 ]; then
        __tadoru_cd "$HOME" || return
        return 0
    fi
    local path
    path=$(zoxide query -- "$@") || return
    __tadoru_cd "$path"
}

# zoxide init defines z and zi itself; replace them with the tadoru versions.
unalias z zi 2>/dev/null
"#,
    );
    for (name, mode, _) in PICK_COMMANDS {
        writeln!(out, "{name}() {{ __tadoru_pick {mode} \"$@\"; }}")?;
    }
    out.push_str("z() { __tadoru_jump \"$@\"; }\n");
    Ok(out)
}

/// Returns `(file name, contents)` for each cmd.exe shim.
pub fn cmd() -> Result<Vec<(String, String)>, Error> {
    let exe = exe_path()?;
    let exe_dir = exe
        .parent()
        .ok_or("cannot determine the directory of tadoru.exe")?
        .to_string_lossy()
        .into_owned();
    let mut files = Vec::new();
    for (name, mode, summary) in PICK_COMMANDS {
        files.push((
            format!("{name}.cmd"),
            cmd_pick(name, mode, summary, &exe_dir),
        ));
    }
    files.push((
        "z.cmd".to_string(),
        cmd_capture(
            "z",
            "jump to a directory from zoxide",
            &exe_dir,
            "zoxide query -- %*",
        ),
    ));
    Ok(files)
}

pub fn write_cmd(dir: &Path) -> Result<Vec<PathBuf>, Error> {
    write_files(dir, cmd()?)
}

fn write_files(dir: &Path, files: Vec<(String, String)>) -> Result<Vec<PathBuf>, Error> {
    std::fs::create_dir_all(dir)?;
    let mut written = Vec::new();
    for (name, body) in files {
        let path = dir.join(name);
        std::fs::write(&path, body)?;
        written.push(path);
    }
    Ok(written)
}

fn cmd_pick(name: &str, mode: &str, summary: &str, exe_dir: &str) -> String {
    cmd_capture(
        name,
        summary,
        exe_dir,
        &format!("tadoru pick --mode {mode}"),
    )
}

fn cmd_capture(name: &str, summary: &str, exe_dir: &str, command: &str) -> String {
    // Run directly: FOR /F's child cmd loses the exit code and reparses arguments.
    // The temporary file holds stdout only; the interactive UI stays on stderr.
    let shortcut = if name == "z" {
        "if \"%~1\"==\"\" goto tadoru_home\n"
    } else if name == "c" {
        "if \"%~1\"==\"-\" if \"%~2\"==\"\" goto tadoru_back\n"
    } else {
        ""
    };
    format!(r#"@echo off
rem {name} [query] - {summary}.
rem Generated by "tadoru init cmd".
setlocal DisableDelayedExpansion
set "PATH=%~dp0;{exe_dir};%PATH%"
set "TADORU_FROM=%CD%"
{shortcut}rem Capture the picker output without reparsing the query in a child cmd.
set "TADORU_QUERY=%*"
for /f "tokens=2 delims=:" %%c in ('chcp') do set "TADORU_CP=%%c"
chcp 65001 >nul
set "TADORU_RESULT=%TEMP%\tadoru-%RANDOM%-%RANDOM%.tmp"
{command} > "%TADORU_RESULT%"
set "TADORU_EXIT=%ERRORLEVEL%"
set "TADORU_PATH="
if "%TADORU_EXIT%"=="0" for /f "usebackq delims=" %%p in ("%TADORU_RESULT%") do set "TADORU_PATH=%%p"
del /q "%TADORU_RESULT%" >nul 2>nul
chcp %TADORU_CP% >nul
if not "%TADORU_EXIT%"=="0" exit /b %TADORU_EXIT%
if not defined TADORU_PATH exit /b 1
:tadoru_move
cd /d "%TADORU_PATH%"
if errorlevel 1 exit /b 2
zoxide add -- "%TADORU_PATH%" 2>nul
if /i "%TADORU_FROM%"=="%CD%" set "TADORU_FROM=%TADORU_PREVIOUS%"
endlocal & cd /d "%TADORU_PATH%" && set "TADORU_PREVIOUS=%TADORU_FROM%"
if errorlevel 1 exit /b 2
exit /b 0
:tadoru_back
if not defined TADORU_PREVIOUS (
    echo tadoru: no previous directory yet 1>&2
    exit /b 2
)
set "TADORU_PATH=%TADORU_PREVIOUS%"
goto tadoru_move
:tadoru_home
set "TADORU_PATH=%USERPROFILE%"
goto tadoru_move
"#).replace('\n', "\r\n")
}

fn exe_path() -> Result<PathBuf, Error> {
    let exe = std::env::current_exe()?;
    Ok(std::path::absolute(exe)?)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn powershell_defines_the_four_commands_and_drops_aliases() {
        let out = powershell().unwrap();
        for f in [
            "function global:c ",
            "function global:cf",
            "function global:z ",
            "function global:zi",
        ] {
            assert!(out.contains(f), "missing {f}");
        }
        assert!(out.contains("Remove-Alias"));
        assert!(out.contains("param([string]$Mode, [string[]]$Query)"));
    }

    #[test]
    fn bash_defines_the_four_commands_with_a_slash_path() {
        let out = bash().unwrap();
        for f in ["\nc() {", "\ncf() {", "\nz() {", "\nzi() {"] {
            assert!(out.contains(f), "missing {f}");
        }
        assert!(out.contains("unalias z zi"));
        let exe_line = out.lines().find(|l| l.contains("pick --mode")).unwrap();
        assert!(
            !exe_line.contains('\\'),
            "exe path must use forward slashes: {exe_line}"
        );
    }

    #[test]
    fn powershell_scripts_prefer_the_exe_next_to_them() {
        let files = powershell_scripts().unwrap();
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["c.ps1", "cf.ps1", "zi.ps1", "z.ps1"]);
        let (_, c) = &files[0];
        // Both names, so a shim written on one platform still finds the
        // binary sitting beside it on another.
        assert!(c.contains("foreach ($candidate in 'tadoru.exe', 'tadoru')"));
        assert!(c.contains("Join-Path $PSScriptRoot $candidate"));
        assert!(c.contains("pick --mode dirs"));
        assert!(c.contains("ValueFromRemainingArguments"));
    }

    #[test]
    fn cmd_emits_four_files_with_the_exe_dir_on_path() {
        let files = cmd().unwrap();
        let names: Vec<&str> = files.iter().map(|(n, _)| n.as_str()).collect();
        assert_eq!(names, ["c.cmd", "cf.cmd", "zi.cmd", "z.cmd"]);
        let (_, c) = &files[0];
        assert!(c.contains("tadoru pick --mode dirs"));
        assert!(c.contains("set \"TADORU_QUERY=%*\""));
        assert!(
            c.contains("set \"PATH=%~dp0;"),
            "the shim folder must come first on PATH"
        );
        assert!(!c.contains("'\""), "exe must not be quoted inside for /f");
        assert!(
            c.split('\n').all(|l| l.is_empty() || l.ends_with('\r')),
            "cmd files use CRLF"
        );
    }
}
